# Stage 1: Build React app
FROM node:20 AS build
WORKDIR /app

# Copy package.json & install
COPY frontend/package*.json ./
RUN npm install

# Copy seluruh source frontend
COPY frontend/. ./

# Copy .env dari root project
COPY .env ./

# Build React app
RUN npm run build

# Stage 2: Serve using Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
